### ISSUE TITLE
hang with request interception + ignoreHTTPSErrors

### ISSUE THREAD

**Issue by rymdhund** [miyakogi/pyppeteer#150]
This hangs:

```
import asyncio
from pyppeteer import launch

async def request_async():
    browser = await launch(
        ignoreHTTPSErrors=True,
        args=['--no-sandbox'],
    )

    async def handle_request(request):
        return await request.continue_()

    page = await browser.newPage()

    await page.setRequestInterception(True)
    page.on('request', lambda req: asyncio.ensure_future(handle_request(req)))

    resp = await page.goto("https://expired.badssl.com/")

loop = asyncio.get_event_loop()
loop.run_until_complete(request_async())
```

The same puppeteer issue: https://github.com/GoogleChrome/puppeteer/issues/1159

Possibly related to #69?

Root cause seems to be upstream bug in chromium. Fixed in chromium r588429

Can we update the chromium version?

**Comment by miyakogi** [comment]
In order to update chromium, we need to change `network_manager.py` (https://github.com/GoogleChrome/puppeteer/commit/1931cb479e02c185a1085e96d678410048340935).
I will try to port this patch tomorrow.

**Comment by rymdhund** [comment]
I see! Thanks for the good work!

**Comment by miyakogi** [comment]
Updated chromium to r588429 on dev branch.

**Comment by rymdhund** [comment]
Yes it works now!

**Comment by phuang0619** [comment]
Should everything work w/o any workaround w/ r588429 now?
I'm running my script on a Mac w/ following specs:
puppeteer: 1.8.0
Chromium: 71.0.3542.0
I reinstall multiple times yesterday so I'm pretty sure it's the rolled back version,
yet, it still hangs on https://example/j_spring_security_check with the following piece of code
with or w/o the argument.
I've tried --enable-features=NetworkService, or --ignore-certificate-errors from other posts, but not much luck.

Rolling back to 1.6.2 does work for me, but the fix for pdf window size in 1.8.0 won't be included.
Any response is appreciated.

`		browser = await puppeteer.launch(ignoreHTTPSErrors=true,{args: ['--enable-features=NetworkService']});
	    page = await browser.newPage();
	    page.on('console', msg => {
	    		console.log(msg.text());
	    });
	    
        await page.setRequestInterception(true);
        page.on('request', request => {
           	request.continue();
        });`

**Comment by miyakogi** [comment]
This is an issue tracker for pyppeteer (python fork of puppeteer), not for puppeteer's.
Puppeteer's issue tracker is [here](https://github.com/GoogleChrome/puppeteer/issues).

**Comment by phuang0619** [comment]
my apologies
