### ISSUE TITLE
Don't add more things to ~/.

### ISSUE THREAD

**Issue by habnabit** [miyakogi/pyppeteer#93]
https://github.com/miyakogi/pyppeteer/blob/19db6ba043613143c958bae9324b392f2a06055b/pyppeteer/launcher.py#L34

Can you please use [appdirs](https://pypi.org/project/appdirs/1.4.3/) or equivalent to not create more dot-directories in my home? As an added bonus, this will DTRT on windows too.

**Comment by miyakogi** [comment]
Thank you for introducing nice library appdirs.
That location has been my concern.
I will check appdirs and will change the location until next release.

**Comment by Xowap** [comment]
The download location has been problematic for me. I use Requests HTML/Pyppeteer on a server and due to my deployment process/server configuration I can't download things to the user's HOME and must rather set a custom download location. I have been [mitigating this issue](https://gist.github.com/Xowap/27979b779d971e8109f52997886434c4) with a monkey patch in my app, but if it was officially configurable (through environment variables, by example) it would be pretty neat.

**Comment by marksteward** [comment]
I disable downloading by always specifying `executablePath='google-chrome'`, and manage installing Chrome outside the app.

**Comment by habnabit** [comment]
@Xowap yeah, appdirs should support that transparently.

**Comment by miyakogi** [comment]
Thank you for discussion.
Anyway, I've changed pyppeteer to use appdirs to find proper directory and pushed to `dev` branch.

I'd like to add an option to change this location, for example `$PYPPETEER_HOME` environment variable.

**Comment by miyakogi** [comment]
Now `$PYPPETEER_HOME` environment variable has been implemented (https://github.com/miyakogi/pyppeteer/commit/bb1dcdec22e2d75c5f4c8c7ee843ba79b96614a0).

**Comment by Xowap** [comment]
That is perfect :+1:
